LINKU_URL = "https://api.linku.la/v2/words"
LINKU_SANDBOX_URL = "https://api.linku.la/v2/sandbox/words"
DB_PATH = "./2025-10-20-trimmed.sqlite"

DAYS = {
    "ALL": 0,
    "2022": 1627776000,
    "2023": 1659312000,
    "2024": 1690848000,
    "2025": 1722470400,
}

INTERFERENCE = {
    # known false positives and unavoidable junk items
    # plus some _probable_ false positives scoring far above their
    # reported/expected use
    "ah",
    "also",
    "amo",
    "an",
    "and",
    "ankaŭ",
    "b",
    "but",
    "c",
    "d",
    "etc",
    "for",
    "hi",
    "i",
    "t",
    "why",
    "hm",
    "uno",
    "i'm",
    "iku",
    "ilu",
    "in",
    "is",
    "it's",
    "j",
    "ja",
    "jaja",
    "jajaja",
    "jajajaja",
    "jajajajaja",
    "jajajajajaja",
    "je",
    "jes",
    "just",
    "from",
    "kiku",
    "h",
    "k",
    "l",
    "latin",
    "le",
    "perhaps",
    "like",
    "lol",
    "m",
    "maybe",
    "me",
    "mesa",
    "muku",
    "min",
    "muti",
    "lapi",
    "na",
    "nani",
    "then",
    "no",
    "not",
    "of",
    "oh",
    "on",
    "or",
    "os",
    "owo",  # emoticon
    "p",
    "paka",
    "pula",
    "puta",
    "r",
    "s",
    "si",
    "so",
    "ta",  # in sandbox technically, but there's no way
    "taka",
    "ten",
    "the",
    "ti",
    "tiki",
    "tiku",
    "tila",
    "timi",
    "tipo",
    "titi",
    "tuki",
    "tula",
    "uli",
    "upi",
    "uwu",  # emoticon
    "vs",
    "w",
    "what's",
    "would",
    "ok",
    "x",
    "xd",  # emoticon
    "y",
    "yeah",
    "yes",
    "i'm",
    "‍",  # zwj; removed in future db revision
}


UCSUR_MAP = {
    "󱤀": "a",
    "󱤁": "akesi",
    "󱤂": "ala",
    "󱤃": "alasa",
    "󱤄": "ale",
    "󱤅": "anpa",
    "󱤆": "ante",
    "󱤇": "anu",
    "󱤈": "awen",
    "󱤉": "e",
    "󱤊": "en",
    "󱤋": "esun",
    "󱤌": "ijo",
    "󱤍": "ike",
    "󱤎": "ilo",
    "󱤏": "insa",
    "󱤐": "jaki",
    "󱤑": "jan",
    "󱤒": "jelo",
    "󱤓": "jo",
    "󱤔": "kala",
    "󱤕": "kalama",
    "󱤖": "kama",
    "󱤗": "kasi",
    "󱤘": "ken",
    "󱤙": "kepeken",
    "󱦀": "kijetesantakalu",
    "󱤚": "kili",
    "󱤛": "kiwen",
    "󱤜": "ko",
    "󱤝": "kon",
    "󱤞": "kule",
    "󱤟": "kulupu",
    "󱤠": "kute",
    "󱤡": "la",
    "󱤢": "lape",
    "󱤣": "laso",
    "󱤤": "lawa",
    "󱤥": "len",
    "󱤦": "lete",
    "󱤧": "li",
    "󱤨": "lili",
    "󱤩": "linja",
    "󱤪": "lipu",
    "󱤫": "loje",
    "󱤬": "lon",
    "󱤭": "luka",
    "󱤮": "lukin",
    "󱤯": "lupa",
    "󱤰": "ma",
    "󱤱": "mama",
    "󱤲": "mani",
    "󱤳": "meli",
    "󱤴": "mi",
    "󱤵": "mije",
    "󱤶": "moku",
    "󱤷": "moli",
    "󱤸": "monsi",
    "󱤹": "mu",
    "󱤺": "mun",
    "󱤻": "musi",
    "󱤼": "mute",
    "󱤽": "nanpa",
    "󱤾": "nasa",
    "󱤿": "nasin",
    "󱥀": "nena",
    "󱥁": "ni",
    "󱥂": "nimi",
    "󱥃": "noka",
    "󱥄": "o",
    "󱥅": "olin",
    "󱥆": "ona",
    "󱥇": "open",
    "󱥈": "pakala",
    "󱥉": "pali",
    "󱥊": "palisa",
    "󱥋": "pan",
    "󱥌": "pana",
    "󱥍": "pi",
    "󱥎": "pilin",
    "󱥏": "pimeja",
    "󱥐": "pini",
    "󱥑": "pipi",
    "󱥒": "poka",
    "󱥓": "poki",
    "󱥔": "pona",
    "󱥕": "pu",
    "󱥖": "sama",
    "󱥗": "seli",
    "󱥘": "selo",
    "󱥙": "seme",
    "󱥚": "sewi",
    "󱥛": "sijelo",
    "󱥜": "sike",
    "󱥝": "sin",
    "󱥞": "sina",
    "󱥟": "sinpin",
    "󱥠": "sitelen",
    "󱥡": "sona",
    "󱥢": "soweli",
    "󱥣": "suli",
    "󱥤": "suno",
    "󱥥": "supa",
    "󱥦": "suwi",
    "󱥧": "tan",
    "󱥨": "taso",
    "󱥩": "tawa",
    "󱥪": "telo",
    "󱥫": "tenpo",
    "󱥬": "toki",
    "󱥭": "tomo",
    "󱥮": "tu",
    "󱥯": "unpa",
    "󱥰": "uta",
    "󱥱": "utala",
    "󱥲": "walo",
    "󱥳": "wan",
    "󱥴": "waso",
    "󱥵": "wawa",
    "󱥶": "weka",
    "󱥷": "wile",
    "󱥸": "namako",
    "󱥹": "kin",
    "󱥺": "oko",
    "󱥻": "kipisi",
    "󱥼": "leko",
    "󱥽": "monsuta",
    "󱥾": "tonsi",
    "󱥿": "jasima",
    "󱦁": "soko",
    "󱦂": "meso",
    "󱦃": "epiku",
    "󱦄": "kokosila",
    "󱦅": "lanpan",
    "󱦆": "n",
    "󱦇": "misikeke",
    "󱦈": "ku",
    "󱦠": "pake",
    "󱦡": "apeja",
    "󱦢": "majuna",
    "󱦣": "powe",
}
